const english_vocabulary = [
    "ability",
    "abroad",
    "absence",
    "absolute",
    "absolutely",
    "academic",
    "accept",
    "access",
    "accident",
    "accommodation",
    "celebrate",
    "determine",
    "enthusiasm",
    "flexible",
    "generation",
    "harmony",
    "integrity",
    "journey",
    "knowledge",
    "luxury",
    "magnificent",
    "necessity",
    "obstacle",
    "passion",
    "quality",
    "reliable",
    "solution",
    "triumph",
    "unique",
    "wisdom",
    "benevolent",
    "courage",
    "delightful",
    "effortless",
    "fantastic",
    "gratitude",
    "happiness",
    "imagination",
    "joyful",
    "kindness",
    "luminous",
    "mysterious",
    "nostalgia",
    "optimism",
    "passionate",
    "radiant",
    "serenity",
    "tranquil",
    "vibrant",
    "wonderful",
    "adventure",
    "balance",
    "curiosity",
    "destination",
    "enthusiastic",
    "forgiveness",
    "gratitude",
    "happiness",
    "inspiration",
    "knowledgeable",
    "liberty",
    "motivation",
    "optimistic",
    "passionate",
    "resilience",
    "success",
    "vibrant",
    "wonderful",
    "youthful",
    "zealous",
    "brilliant",
    "effervescent",
    "graceful",
    "harmonious",
    "insightful",
    "jubilant",
    "knowledgeable",
    "luminous",
    "mesmerizing",
    "nurturing",
    "optimistic",
    "picturesque",
    "quintessential",
    "resplendent",
    "serendipity",
    "transcendent",
    "unforgettable",
    "veracious",
    "whimsical",
    "xenial",
    "youthful",
    "zestful",
    "ambition",
    "ambitious",
    "both",
    "to threaten",
    "househusband",
    "love",
    "illiterate",
    "tiptoe",
    "host",
    "indigo",
    "encourage",
    "take heart",
    "leap year",
    "gap year",
    "satellite dish",
    "previous",
    "before",
    "ancient",
    "antonyms",
    "advertised",
    "turn off",
    "gadget",
    "electrical appliances",
    "turn up",
    "look",
    "appearance",
    "celery",
    "to flatten",
    "crush",
    "clap",
    "to apply",
    "bet",
    "to support",
    "to lean",
    "support",
    "to learn",
    "learn by heart",
    "learner",
    "hurry"
]

const spanish_vocabulary = [
    "habilidad",
    "en el extranjero",
    "ausencia",
    "absoluto",
    "absolutamente",
    "académico",
    "aceptar",
    "acceso",
    "accidente",
    "alojamiento",
    "celebrar",
    "determinar",
    "entusiasmo",
    "flexible",
    "generación",
    "armonía",
    "integridad",
    "viaje",
    "conocimiento",
    "lujo",
    "magnífico",
    "necesidad",
    "obstáculo",
    "pasión",
    "calidad",
    "confiable",
    "solución",
    "triunfo",
    "único",
    "sabiduría",
    "benévolo",
    "coraje",
    "encantador",
    "sin esfuerzo",
    "fantástico",
    "gratitud",
    "felicidad",
    "imaginación",
    "alegre",
    "bondad",
    "luminoso",
    "misterioso",
    "nostalgia",
    "optimismo",
    "apasionado",
    "radiante",
    "serenidad",
    "tranquilo",
    "vibrante",
    "maravilloso",
    "aventura",
    "equilibrio",
    "curiosidad",
    "destino",
    "entusiasta",
    "perdón",
    "gratitud",
    "felicidad",
    "inspiración",
    "conocedor",
    "libertad",
    "motivación",
    "optimista",
    "apasionado",
    "resiliencia",
    "éxito",
    "vibrante",
    "maravilloso",
    "juvenil",
    "apasionado",
    "brillante",
    "efervescente",
    "gracioso",
    "armónico",
    "perspicaz",
    "jubiloso",
    "conocedor",
    "luminoso",
    "hipnotizante",
    "nutritivo",
    "optimista",
    "pintoresco",
    "quintesencial",
    "resplandeciente",
    "serendipia",
    "trascendente",
    "inolvidable",
    "veraz",
    "caprichoso",
    "hospitalario",
    "juvenil",
    "vigoroso",
    "adorable",
    "deslumbrante",
    "cautivador",
    "deslumbrante",
    "éxtasis",
    "fascinante",
    "gracioso",
    "celestial",
    "idílico",
    "jovial",
    "entusiasta",
    "animado",
    "hipnotizante",
    "noble",
    "sobresaliente",
    "pacífico",
    "pintoresco",
    "radiante",
    "sereno",
    "tranquilo",
    "edificante",
    "vívido",
    "maravilloso",
    "juvenil",
    "apasionado",
    "ambición",
    "ambicioso",
    "ambos",
    "amenazar",
    "amo de casa",
    "amor",
    "analfabeto",
    "andar de puntillas",
    "anfitrion",
    "añil",
    "animar",
    "animate",
    "año bisiesto",
    "año sabático",
    "antena parabólica",
    "anterior",
    "antes de",
    "antiguo",
    "antónimos",
    "anunciado",
    "apagar",
    "aparato",
    "aparatos eléctricos",
    "aparecer",
    "apariencia",
    "apariencia física ",
    "apio",
    "aplanar",
    "aplastar",
    "aplaudir",
    "aplicar",
    "apostar",
    "apoyar",
    "apoyarse",
    "apoyo",
    "aprender",
    "aprender de memoria",
    "aprendiz",
    "apresurarse"
]

const word = document.getElementById("word");

function generateWord() {
    let index = getRandomNumber(0, english_vocabulary.length);
    word = spanish_vocabulary[index]
}

function getRandomNumber(min, max) {
    return Math.random() * (max - min) + min;
  }